// ============================================================================
// DATA PACK — verbatim from Assignment 2 Data Pack (Veridian Corp, IT Support)
// This is the ONLY source of policy/ground truth the agent is allowed to use.
// ============================================================================

const KB = [
  {
    id: "KB-01",
    title: "Password Reset",
    text: "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required."
  },
  {
    id: "KB-02",
    title: "VPN Access",
    text: "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."
  },
  {
    id: "KB-03",
    title: "Laptop Replacement",
    text: "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
  },
  {
    id: "KB-04",
    title: "Software Installation Requests",
    text: "Standard software (listed in the approved catalog) can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days."
  },
  {
    id: "KB-05",
    title: "Printer Troubleshooting",
    text: "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag."
  },
  {
    id: "KB-06",
    title: "Email Mailbox Quota",
    text: "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB."
  },
  {
    id: "KB-07",
    title: "Guest Wi-Fi Access",
    text: "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required."
  },
  {
    id: "KB-08",
    title: "Expense Software Access",
    text: "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists."
  },
  {
    id: "KB-09",
    title: "Security Incident Reporting",
    text: "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees."
  },
  {
    id: "KB-10",
    title: "Work-From-Home Equipment",
    text: "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."
  },
  {
    id: "ASSET-POLICY",
    title: "Asset Management Policy (Extract) — Finance & Assets, updated Q2 2026",
    text: "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
  }
];

function kbById(id) { return KB.find(k => k.id === id); }

// Employee requests from Section 2 of the data pack — used to power the quick chips.
const EMPLOYEE_REQUESTS = [
  { id: "REQ-01", name: "Aditi Sharma", email: "aditi.sharma@veridiancorp.example", date: "Mon 21 Sep", text: "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now." },
  { id: "REQ-02", name: "Vikram Chawla", email: "vikram.chawla@veridiancorp.example", date: "Mon 21 Sep", text: "Can I get Wi-Fi access for a guest visiting our office tomorrow?" },
  { id: "REQ-03", name: "Karan Mehta", email: "karan.mehta@veridiancorp.example", date: "Mon 21 Sep", text: "I'm locked out of my account, tried my password 6 times." },
  { id: "REQ-04", name: "Ritu Bhatia", email: "ritu.bhatia@veridiancorp.example", date: "Tue 22 Sep", text: "Need approval to install a data-analysis tool that's not in the software catalog." },
  { id: "REQ-05", name: "Sanjay Oberoi", email: "sanjay.oberoi@veridiancorp.example", date: "Tue 22 Sep", text: "My VPN stopped working this morning, says credentials expired." },
  { id: "REQ-06", name: "Meera Iyer", email: "meera.iyer@veridiancorp.example", date: "Tue 22 Sep", text: "Printer on the 3rd floor keeps showing \"paper jam\" even though there's no jam." },
  { id: "REQ-07", name: "Farhan Ali", email: "farhan.ali@veridiancorp.example", date: "Wed 23 Sep", text: "I've started working from home 4 days a week, how do I get a monitor?" },
  { id: "REQ-08", name: "Ananya Reddy", email: "ananya.reddy@veridiancorp.example", date: "Wed 23 Sep", text: "I think I got a phishing email asking for my login — forwarding it to a few teammates to check." },
  { id: "REQ-09", name: "Rohit Desai", email: "rohit.desai@veridiancorp.example", date: "Wed 23 Sep", text: "My mailbox is full and I can't send emails." },
  { id: "REQ-10", name: "Kavya Pillai", email: "kavya.pillai@veridiancorp.example", date: "Wed 23 Sep", text: "Can someone give me admin access to the finance reporting server? Need it urgently for month-end." },
  { id: "REQ-11", name: "Nikhil Bansal", email: "nikhil.bansal@veridiancorp.example", date: "Thu 24 Sep", text: "New contractor joining my team next week, they'll need VPN access." },
  { id: "REQ-12", name: "Sneha Kulkarni", email: "sneha.kulkarni@veridiancorp.example", date: "Thu 24 Sep", text: "I can't log into the expense tool, keeps saying invalid credentials." },
  { id: "REQ-13", name: "Aman Gupta", email: "aman.gupta@veridiancorp.example", date: "Thu 24 Sep", text: "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement." },
  { id: "REQ-14", name: "Tanya Chopra", email: "tanya.chopra@veridiancorp.example", date: "Fri 25 Sep", text: "Requesting approval to install a browser extension for productivity tracking." },
  { id: "REQ-15", name: "Rahul Menon", email: "rahul.menon@veridiancorp.example", date: "Fri 25 Sep", text: "hey can you help, its not working" }
];

// Existing ticket queue (Section 3) — seeded as history. Closed tickets are shown
// as read-only precedent; active ones are shown as already in flight.
const SEED_TICKETS = [
  { id: "TK-1042", employee: "R. Verma", summary: "VPN credential expired", category: "KB-02", status: "Resolved", closed: true,
    audit: [{ ts: "2026-09-15 09:10", actor: "Agent", action: "Self-renewal instructions issued per KB-02." },
            { ts: "2026-09-15 09:22", actor: "R. Verma", action: "Confirmed renewed." }] },
  { id: "TK-1043", employee: "S. Iyer", summary: "Laptop replacement (3.2 yrs old)", category: "KB-03", status: "Approved — pending fulfillment", closed: false,
    audit: [{ ts: "2026-09-10 11:00", actor: "S. Iyer", action: "Requested replacement, device age 3.2 years." },
            { ts: "2026-09-11 14:30", actor: "IT", action: "Verified hardware condition; early-replacement case under ASSET-POLICY (4-yr cycle)." },
            { ts: "2026-09-12 10:05", actor: "Finance", action: "Sign-off granted for early replacement." },
            { ts: "2026-09-12 10:06", actor: "IT", action: "Approved — pending fulfillment." }] },
  { id: "TK-1044", employee: "A. Khan", summary: "Non-catalog software request", category: "KB-04", status: "Pending Security review", closed: false,
    audit: [{ ts: "2026-09-16 08:40", actor: "A. Khan", action: "Requested install of non-catalog tool." },
            { ts: "2026-09-16 08:41", actor: "Agent", action: "Routed to IT Security review per KB-04 (3–5 business days)." }] },
  { id: "TK-1045", employee: "P. Joshi", summary: "Mailbox quota increase", category: "KB-06", status: "Approved at 35GB", closed: true,
    audit: [{ ts: "2026-09-08 09:00", actor: "P. Joshi", action: "Requested quota increase." },
            { ts: "2026-09-08 13:15", actor: "Manager", action: "Approved increase to 35GB (within 50GB cap)." }] },
  { id: "TK-1046", employee: "M. Das", summary: "Printer paper jam, floor 2", category: "KB-05", status: "Resolved", closed: true,
    audit: [{ ts: "2026-09-09 10:00", actor: "M. Das", action: "Reported persistent paper jam." },
            { ts: "2026-09-09 10:40", actor: "IT", action: "Spooler restarted, tray realigned. Issue resolved." }] },
  { id: "TK-1047", employee: "K. Singh", summary: "Home office equipment request", category: "KB-10", status: "Pending Finance", closed: false,
    audit: [{ ts: "2026-09-17 09:30", actor: "K. Singh", action: "Requested chair + monitor, WFH 4 days/week." },
            { ts: "2026-09-17 09:35", actor: "Manager", action: "Sign-off granted." },
            { ts: "2026-09-17 09:36", actor: "Agent", action: "Routed to Finance for processing per KB-10." }] },
  { id: "TK-1048", employee: "T. Rao", summary: "Phishing email reported", category: "KB-09", status: "Escalated to Security — under investigation", closed: false,
    audit: [{ ts: "2026-09-18 12:05", actor: "T. Rao", action: "Reported suspected phishing email." },
            { ts: "2026-09-18 12:05", actor: "Agent", action: "Auto-escalated to security@veridian-corp.example per KB-09." }] },
  { id: "TK-1049", employee: "V. Nambiar", summary: "Password reset", category: "KB-01", status: "Resolved", closed: true,
    audit: [{ ts: "2026-09-14 15:00", actor: "V. Nambiar", action: "Requested reset via self-service portal." },
            { ts: "2026-09-14 15:02", actor: "Agent", action: "Confirmed self-service reset per KB-01." }] },
  { id: "TK-1050", employee: "J. Fernandes", summary: "Admin access request", category: "OTHER", status: "Rejected — no business justification provided", closed: true,
    audit: [{ ts: "2026-09-05 09:00", actor: "J. Fernandes", action: "Requested admin access to internal server." },
            { ts: "2026-09-05 09:10", actor: "Agent", action: "No governing self-service policy found; flagged as high-risk privileged access." },
            { ts: "2026-09-06 11:00", actor: "System Owner", action: "Rejected — no business justification provided." }] },
  { id: "TK-1051", employee: "L. Menon", summary: "Guest Wi-Fi issued", category: "KB-07", status: "Resolved", closed: true,
    audit: [{ ts: "2026-09-19 08:50", actor: "L. Menon", action: "Generated guest Wi-Fi at front-desk kiosk per KB-07." }] }
];

const TODAY_LABEL = "Fri 25 Sep 2026";
